### ISSUE TITLE
Actualizar Typeform Busqueda de Tiendas en la landing

### ISSUE THREAD

**Issue by anothernocoder** [gio-moros/landings#17]
--------------------------
Email Andres Parra
---------------------------
Buenos días Equipo; espero estén muy bien.

A continuación comparto el nuevo typeform de buscamos tiendas; donde se ha actualizado el diseño y contenido del mismo.

[@Samuel Villegas](mailto:samuel@cocomercado.com) agradezco me puedas colaborar con la actualización del link en el footer o pie de Pagina web "Aliados Comerciales" https://aliados.cocomercado.com/tiendas en el Boton del Banner "registrate ahora" y el botón del header " Registrate ya".  https://cocomarket.typeform.com/aliadoscoco22

Por favor avísame cuando el cambio sea aplicado.

[@Isabella Muller](mailto:isabella@cocomercado.com) Al momento que pongamos a correr el ads que estos sean dirigidos al link  https://cocomarket.typeform.com/aliadoscoco22

Sírvase también para que los demás integrantes del equipo, lo tengan en cuenta cuando tengan solicitudes de cómo aperturar una tienda en Coco.

Quedo atento a cualquier duda o comentario; Saludos.

**Comment by NataliRC** [comment]
Pruebas realizadas
Resultado: Exitoso

Navegador web - Google Chrome - Versión 107.0.5304.88
Navegador web - Microsoft Edge - Versión 107.0.1418.26
Mobile - iPhone 14 v16.0 - Safari
Mobile - Samsung Galaxy S22 Ultra v12.0 - Google Chrome

Pasos de reproducción
1. Abrir la web https://aliados.cocomercado.com/tiendas
2. Dar click en "¡Regístrate ahora!" y "¡Regístrate ya!" en todos los botones de la web
3. Ver que el link donde redirija sea https://cocomarket.typeform.com/aliadoscoco22

Evidencia:

https://user-images.githubusercontent.com/113143707/200097803-21e82eff-3453-4391-81aa-f3d6bc8a3dd3.webm
